export const APP_EVENTS = {
  changePaginationPage: 'changePaginationPage',
  setCategoryProducts: 'setCategoryProducts',
  searchProducts: 'searchProducts',
  storage: 'storage',
  changeRoute: 'changeRoute',
  activeRoute: 'activeRoute',
  changeTab: 'changeTab',
  createCategory: 'createCategory',
  createProduct: 'createProduct',
  createBlog: 'createBlog',
  idProduct: 'idProduct',
  signUp: 'signUp',
  signIn: 'signIn',
  authorizeUser: 'authorizeUser',
  searchOn: 'searchOn',
};
